name: CD

on:
  push:
    branches:
      - "new"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RCA package
        uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/performance-analyzer-rca
          path: ./tmp/rca
      - name: Checkout Performance Analyzer package
        uses: actions/checkout@v2
        with:
          path: ./tmp/pa
      - name: Set up JDK 1.12
        uses: actions/setup-java@v1
        with:
          java-version: 1.12
      - name: Build RCA with Gradle
        working-directory:  ./tmp/rca
        run: ./gradlew build -x test
      - name: Publish RCA jar to maven local
        working-directory: ./tmp/rca
        run: ./gradlew publishToMavenLocal
      - name: Build PA gradle using the new RCA jar
        working-directory: ./tmp/pa
        run: rm licenses/performanceanalyzer-rca-1.12.jar.sha1
      - name: Update SHA
        working-directory: ./tmp/pa
        run: ./gradlew updateShas
      - name: Build Artifacts
        working-directory: ./tmp/pa
        run: |
          ./gradlew build buildDeb buildRpm --refresh-dependencies -Dbuild.snapshot=false -x javadoc
          mkdir artifacts
          artifact=`ls build/distributions/*.zip`
          rpm_artifact=`ls build/distributions/*.rpm`
          deb_artifact=`ls build/distributions/*.deb`
          cp $artifact artifacts/
          cp $rpm_artifact artifacts/
          cp $deb_artifact artifacts/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Upload Artifacts to S3
        working-directory: ./tmp/pa
        run: |
          aws s3 cp artifacts/*.deb s3://staging.artifacts.opendistroforelasticsearch.amazon.com/repos/all-old-debs/